### ISSUE TITLE
Problem to install

### ISSUE THREAD

**Issue by prestancedesign** [aurelien-rainone/tmux-gitbar#33]
Hi,

After installation, I have only this icon on tmux status bar.
![image](https://cloud.githubusercontent.com/assets/1840522/18127148/d510c470-6f7e-11e6-8683-1674f04f7acc.png)

I tried to change zsh to bash, minimal tmux.conf, new ubuntu user but I have only the same icon.
Did I forget something?

**Comment by arl** [comment]
Can you show your tmux.conf and in which directory did you install
tmux-gitbar?

**Comment by prestancedesign** [comment]
Thx for your response.

I install in ~/.tmux-gitbar.

My tmux.conf : 
@[tmux.txt](https://github.com/aurelien-rainone/tmux-gitbar/files/447121/tmux.txt)

Clarification, I also tried with an empty basic tmux.conf on new Ubuntu user and the same problem persist.

**Comment by arl** [comment]
You're welcome.
Thanks for the information, so you tried with an empty tmux.conf,
containing only what is required for tmux-gitbar, and you got the same
problem? Can you confirm you restarted tmux after cleaning the
configuration file, and that you didn't have any tmux sessions running?
I will need also your tmux version.
Does your repository contain submodules? Do you have the same result by
entering into a newly created directory, after typing git init?
That's a bunch of questions but I will need more context in order to help
you solve that, for now I have honestly no clue ;-)

**Comment by prestancedesign** [comment]
> Thanks for the information, so you tried with an empty tmux.conf, containing only what is required for tmux-gitbar, and you got the same problem? 

Yes.

Can you confirm you restarted tmux after cleaning the configuration file, and that you didn't have any tmux sessions running?

Yes, I do tmux kill-server; tmux. Even better, I start from scratch in new created user (no dotfile config, bash, etc) on my Ubuntu.

> I will need also your tmux version.

tmux 2.1

> Does your repository contain submodules? 

Yes.

> Do you have the same result by entering into a newly created directory, after typing git init?

Yes.

**Comment by arl** [comment]
Ok thanks for the detailed reporting.
I now should be able to reproduce

**Comment by prestancedesign** [comment]
Thank you @aurelien-rainone !
For my side, i'll update tmux 2.2.

**Comment by prestancedesign** [comment]
Same problem with version 2.2.
Perhaps a track, when I source directlty tmux-gitbar.conf, I have this warning : 
`/home/user/.tmux-gitbar/tmux-gitbar.conf:11: unknown command: readonly`

**Comment by arl** [comment]
Are you not using bash?

**Comment by arl** [comment]
If you are not using bash but a different shell, tell me which one and I'll add
support for it

**Comment by prestancedesign** [comment]
I use zsh, but I tested with bash and nothing better. :(

**Comment by arl** [comment]
When you say you tested with zsh, do you mean you changed the default shell
of your system (with `chsh` command)? Just to confirm the problem comes
from tmux and not from the fact tmux uses another shell, would you please
tell me what is the value of the $SHELL env var when you are in tmux and
the problem happens.
The fact that sourcing tmux.conf raises an error about the readonly keyword
not available seems significative of an old version of bash that does not
support readonly, or another shell

**Comment by prestancedesign** [comment]
Hi,

As I said before, I create a new Ubuntu user on my computer so I start from scratch with default Ubuntu shell :
- `echo $SHELL` = /bin/bash
- `bash --version`  = GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)

My bad for readonly warning. It's happening when I do `tmux source-file` instead of `source` command :\
![image](https://cloud.githubusercontent.com/assets/1840522/18163198/1bf1ef70-703a-11e6-9ce7-caf939f6b15a.png)

With source command no warning ! ;)

**Comment by arl** [comment]
I also tried tmux-gitbar with latest tmux, version 2.2, and no problem. There must be something obvious that is different in your configuration I presume but I can't seem to see what. tmux-gitbar is tested on travis boxes, so with a really basic environment.
Last thing I can try, because i would really like to understand what is happening and how to fix this, for you and other people that may have the same problem, is to analyze the trace produced by:

```
bash -x update-gitbar 2> trace
```

Run this when you are in tmux-gitbar root dir and copy the generated `trace`  file

**Comment by prestancedesign** [comment]
> Last thing I can try, because i would really like to understand what is happening and how to fix this

Thank you. I appreciate that.

Here is the trace file of an default new Ubuntu user **test** with default .bashrc and .tmux.conf with only the line to source tmux-gitbar :
[trace.tar.gz](https://github.com/aurelien-rainone/tmux-gitbar/files/453330/trace.tar.gz)

**Comment by arl** [comment]
OMG...I need holydays I guess, now it seems so obvious by looking at your first comment with the screenshot, I honestly thought about it the 1st time but didnt get to the bottom of it.  
So the default value for the right part of the tmux status string, on your version of tmux at least, seems to be `' "#{=21:pane_title}" %H:%M %d-%b-%y'`, that's why you get some things written on the right of the status bar even if you didn't set nothing in `tmux.conf`. But this string expands to something quite long, avoiding the tmux-gitbar to show entirely.

So you have 2 solutions:
- expand the length of the right status string to 100 for example, by adding this to `tmux.conf`:

``` bash
set -g status-right-length 100
```
- or set something different for your right status string, empty is also ok:

``` bash
set -g status-right ""
```

I guess I should add something about that on the README...
Thank you!

**Comment by arl** [comment]
I added a troubleshooting section to the README: 875b0c4

**Comment by prestancedesign** [comment]
Well done ! ;)
Thank you @aurelien-rainone
