### ISSUE TITLE
Some errors occur when update-gitbar called in the initial git directory

### ISSUE THREAD

**Issue by kyoh86** [aurelien-rainone/tmux-gitbar#51]
```
$ cd /tmp
$ mkdir foobar
$ cd foobar
$ git init
$ ~/.tmux-gitbar/update-gitbar
/Users/foo/.tmux-gitbar/lib/tmux-gitbar.sh: line 128: test: on: integer expression expected
/Users/foo/.tmux-gitbar/lib/tmux-gitbar.sh: line 128: test: master: integer expression expected
/Users/foo/.tmux-gitbar/lib/tmux-gitbar.sh: line 128: test: _NO_REMOTE_TRACKING_: integer expression expected
/Users/foo/.tmux-gitbar/lib/tmux-gitbar.sh: line 128: test: ^: integer expression expected
```

env: tmux 2.6, zsh 5.4.2 (x86_64-apple-darwin16.7.0)
out of context: I'm troubled since I cannot update gitbar automatically...

**Comment by arl** [comment]
Hi Kyoichiro
Tmux-gitbar is currently only supported for bash shell.
Thanks for reporting anyway.


On 18 Oct 2017 04:07, "Kyoichiro Yamada" <notifications@github.com> wrote:

$ cd /tmp
$ mkdir foobar
$ cd foobar
$ git init
$ ~/.tmux-gitbar/update-gitbar
/Users/yamada/.tmux-gitbar/lib/tmux-gitbar.sh: line 128: test: on:
integer expression expected
/Users/yamada/.tmux-gitbar/lib/tmux-gitbar.sh: line 128: test: master:
integer expression expected
/Users/yamada/.tmux-gitbar/lib/tmux-gitbar.sh: line 128: test:
_NO_REMOTE_TRACKING_: integer expression expected
/Users/yamada/.tmux-gitbar/lib/tmux-gitbar.sh: line 128: test: ^:
integer expression expected

env: tmux 2.6, zsh 5.4.2 (x86_64-apple-darwin16.7.0)
out of context: I'm troubled since I cannot update gitbar automatically...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aurelien-rainone/tmux-gitbar/issues/51>, or mute the
thread

**Comment by kyoh86** [comment]
Thank you for your response! it's unfortunate...

**Comment by arl** [comment]
I'm sure that supporting zsh must not be so difficult, I'm open to a Pull
request for that but don't have any time for that myself at the moment.
